### PR TITLE
MNT: Re-rendered with conda-smithy 1.7.0

### PR DESCRIPTION
**Pull request by CJ-Wright**
Fixes https://github.com/conda-forge/pretend-feedstock/issues/2

python 3.6 support

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@conda-forge/pretend Can I please get a merge and/or addition to the write access membership?

**Comment by jakirkham** [comment]
Weird the permissions got fouled up somehow. Could you please try re-rendering again and/or remove the executable permissions?

**Comment by CJ-Wright** [comment]
Where are the executable permissions for me to remove?

**Comment by jakirkham** [comment]
So if you click on the files tab, GitHub will show you something like `100644 → 100755`. This tells you the permissions changed, which needs to be changed. Also I highly suspect new files got added with executable permissions (e.g. `.gitattributes`). So please check them on the command line as well. In short, only the contents of `ci_support` should have executable permissions. Everything else should only have read/write permissions.

**Comment by jakirkham** [comment]
Related to issue ( https://github.com/conda-forge/conda-smithy/issues/424 ).

**Comment by CJ-Wright** [comment]
see #4

**Pull request closed without merging**
