### PR TITLE
Add @CJ-Wright

### PR DESCRIPTION
**Pull request by jakirkham**
Adding @CJ-Wright as a maintainer.

Please let us know if this ok/what you intended, @CJ-Wright. Thanks.

### CODE REVIEW

**Comment by sodre** [comment]
@CJ-Wright that would be perfect. It would be greater to have more than one person keeping track of the project.

**Comment by jakirkham** [comment]
Yeah, I received a notification to this effect that @CJ-Wright was interested in joining the GitHub team maintaining this package. As this is the standard way of doing that, figured I'd put this together. Though could be an errant click so wanted to check. 😉

**Comment by CJ-Wright** [comment]
Yes I'd like to be on the package!

**Review by CJ-Wright — COMMENTED** [review]
👍

**Comment by jakirkham** [comment]
Thanks everyone. FWIW was working on some fixes to the team update script. So it looks like that resulted in getting you added right away. Typically it can be up to 24hrs before a team addition occurs as we run team updates once a day currently. In the future, that may change as we have discussed doing this process asynchronously.

**Pull request merged**
